sudo: false
dist: trusty

language: php
php:
  - '5.6'
  - '7.0'

before_script:
  - cd www && cp settings.php.dist settings.php && cd ../tests

script:
  - phpunit --bootstrap test_module.php

env:
  - DB=mysql
